# Dockerfile.base
FROM python:3.9-slim

WORKDIR /app

# Instala dependencias básicas
RUN apt-get update && apt-get upgrade -y && apt-get install -y perl-base zlib1g && rm -rf /var/lib/apt/lists/*

# Versión corregida de perl-basezlib1g=1:1.2.13.dfsg-2 \       # Versión corregida de zlib1g&& rm -rf /var/lib/apt/lists/*

# Copia los requisitos e instala las dependencias
COPY requirements.txt .
RUN pip install -r requirements.txt

# Crea un usuario no root
RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

# Define un HEALTHCHECK para verificar el estado de la aplicación
HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
  CMD curl -f http://localhost/ || exit 1

CMD ["python"]