# Dockerfile.base
FROM python:3.9-slim

WORKDIR /app

# Instala dependencias básicas
RUN pip install --upgrade pip

# Copia los requisitos e instala las dependencias
COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["python"]