name: Base Image CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      # 3. SAST - Cody Analysis with Semgrep
      - name: SAST - Run Semgrep
        run: | 
         pip install semgrep
         semgrep --config=auto --error

      # 4. SAST - Cody Analysis with Checkov
      - name: SAST - Run Checkov 
        run: |
         pip install checkov
         checkov -f Dockerfile.base --quiet

      # 5. Build image Dockerfile.base
      - name: Build Docker image
        run: docker build -t base-image:latest -f Dockerfile.base .

      # 6. SAST - Docker Analysis with trivy
      - name: SAST - Scan Docker image with Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy image --ignorefile .trivyignore --severity HIGH,CRITICAL base-image:latest

      # 7. Push and Deploy
      - name: Push Docker image (if on main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag base-image:latest ${{ secrets.DOCKER_HUB_USERNAME }}/base-image:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/base-image:latest