name: Base Image CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t base-image:latest -f Dockerfile.base .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'base-image:latest'
          exit-code: 1
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: Scan Docker image with Snyk
        uses: snyk/actions/docker@master
        with:
          image: base-image:latest
          args: --severity-threshold=high
          token: ${{ secrets.SNYK_TOKEN }}

      - name: Push Docker image (if on main branch)
        if: github.ref == 'refs/heads/main'
        run: docker push base-image:latest